//ALERT ACTIONS
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//REGISTER ACTIONS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//USER VALIDATION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

//LOGIN VALIDATION
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//LOGOUT ACTION
export const LOGOUT = "LOGOUT";

//PROFILE ACTIONS
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

// Entry actions
export const CREATE_ENTRY = "CREATE_ENTRY";
export const GET_ENTRY = "GET_ENTRY";
export const GET_ENTRIES = "GET_ENTRIES";
export const ENTRY_ERROR = "ENTRY_ERROR";


